# 项目相关配置
pts:
  # 名称
  name: achilles
  # 版本
  version: 2.2.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/achilles/uploadPath，Linux配置 /home/achilles/uploadPath）
  profile: /var/achilles-pts-docker/back/data/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.qh.venus: debug
    org.springframework: info
# Spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: ${back.spring.datasource.druid.master.url}
        username: ${back.spring.datasource.druid.master.username}
        password: ${back.spring.datasource.druid.master.password}
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: ${back.spring.redis.host}
    # 端口，默认为6379
    port: ${back.spring.redis.port}
    # 密码
    password: ${back.spring.redis.password}
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    #配置rabbitMq 服务器
  rabbitmq:
    host: ${back.spring.rabbitmq.host}
    port: ${back.spring.rabbitmq.port}
    username: ${back.spring.rabbitmq.username}
    password: ${back.spring.rabbitmq.password}
    publisher-confirms: true
    virtual-host: /
    #消费端
    listener:
      simple:
        acknowledge-mode: manual
        #初始连接数量
        concurrency: 5
        #最大连接数量
        max-concurrency: 10
        #每一次发送到消费者的消息数量
        prefetch: 250
  flyway:
    # 启用或禁用 flyway
    enabled: ${back.spring.flyway.enabled}
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
# token配置
token:
  # 令牌自定义标识
  header: token
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.qh.venus.achilles.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  type-handlers-package: com.qh.venus.achilles.framework.mysql.handler

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/pts/sys/*
dfs:
  path: /var/achilles-pts-docker/back/data/uploadPath/
  #对外开放的静态资源路径  勿轻易改动
  openPath: /var/achilles-pts-docker/back/data/uploadPath/static/
  domain: ${back.dfs.domain}
serialnumber:
  # redis,db
  type: db
# 代码生成
gen:
  # 作者
  author: qh_venus
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.qh.venus.achilles.pts
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
license:
  licensePath: /var/achilles-pts-docker/back/data/uploadPath/license_revert.lic
  pubKeyPath:  /var/achilles-pts-docker/back/data/uploadPath/pub_key.txt
flow:
  handler: com.qh.venus.achilles.pts.flow.builder.CustomFlowHandler
jodconverter:
  local:
    enabled: true
    format-options:
      html:
        store:
          text:
            FilterOptions: EmbedImages
      xhtml:
        store:
          text:
            FilterOptions: EmbedImages
xxl:
  job:
    admin:
      addresses: ${back.xxl.job.admin.addresses}
    accessToken: xa-venus@2020
    executor:
      appname: achilles-job
      address:
      ip:
      port: 9999
      logpath: /var/achilles-pts-docker/back/logs/achilles-job/jobhandler
      logretentiondays: 30
guacamole:
  serverHostname: ${back.guacamole.serverHostname}
  serverPort: ${back.guacamole.serverPort}